FROM node:21 As build

# Create app directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
COPY package*.json ./

RUN npm install

# Copy local code to the container image.

COPY . ./

RUN npm run build

CMD ["npm", "start"]

EXPOSE 80

